name: http_rest
description: A robust networking library for Dart and Flutter, simplifies HTTP interactions, provides tools for lightweight versatility.

version: 1.0.0-alpha.3
homepage: https://github.com/RobertApikyan/http_rest
repository: https://github.com/RobertApikyan/http_rest

topics:
  - network
  - http
  - rest

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dartdoc: ^6.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
